import type { Metadata } from "next";
import "./globals.css";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import { Chivo } from 'next/font/google';
import './styles.css';

const chivo = Chivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-chivo',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chivo.variable}>
        {children}
      </body>
    </html>
  )
}
